name: Deploy on Tag

permissions:
  contents: write

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  create-tag:
    if: github.event.pull_request.merged == true
    name: Create Version Tag
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag.outputs.name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Generate Tag Name
        id: tag
        run: |
          props=$(cat app-version.properties)
          version_major=$(echo "$props" | grep -E "version_major=" | cut -d'=' -f2)
          version_minor=$(echo "$props" | grep -E "version_minor=" | cut -d'=' -f2)
          version_patch=$(echo "$props" | grep -E "version_patch=" | cut -d'=' -f2)
          tag="v$version_major.$version_minor.$version_patch"
          echo "Generated tag: $tag"
          echo "name=$tag" >> "$GITHUB_OUTPUT"

      - name: Push Git Tag
        run: |
          git fetch --tags
          git tag ${{ steps.tag.outputs.name }}
          git push origin ${{ steps.tag.outputs.name }}

  build:
    runs-on: ubuntu-24.04
    needs: [create-tag]
    steps:
    - uses: actions/checkout@v4
    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
     #Login Github Container Registry
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Push to Github Container Registry
    - name: Push to Github Container Registry
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          gunawand/learn-git-tag:latest
          gunawand/learn-git-tag:${{ needs.create-tag.outputs.tag_name }}